server:
  port: 8103
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: openblocks-teams
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/infra_teams
    username: infra_user
    password: infra_pwd
    hikari:
      schema: public
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 256
          plan_parameter_metadata_max_size: 128
        criteria:
          literal_handling_mode: BIND
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    user: infra_user
    password: infra_pwd
    default-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8534/realms/infra/protocol/openid-connect/certs
          issuer-uri: http://localhost:8534/realms/infra

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    enable-b3-propagation: true